### ISSUE TITLE
[URGENT] Disabling malicious redirect http://yuren.me/QnZYED

### ISSUE THREAD

**Issue by jdrangosch** [xyTom/Url-Shorten-Worker#63]
Hi Team

Please note that a phishing URL shortener registered through your service is being used to redirect to a phishing attack. It is available at the following URL:

http://yuren.me/QnZYED

Which will redirect to the following website:

https://accesspoint01.challengedrumstreet.ru/

Which is currently conducting a phishing attack against the users of this website:

https://vystarcu.org/

Please assist us with Disabling it as soon as possible, we appreciate your swift response in this regard. If you require any additional information, please do not hesitate to contact me at julian.drangosch@phishfort.com

**Comment by xyTom** [comment]
Hi Julian,

Thank you for bringing this issue to our attention. However, I regret to inform you that we cannot take direct action to take down the link in question, as it does not belong to one of the instances we manage. This is because the URL shortener is an open-source project, and anyone can deploy the service using the project's source code.

Upon preliminary investigation, it appears that the URL shortener instance being exploited is deployed by Github user  @yuren0 (corresponding repository address: https://github.com/yuren0/Url-Shorten-Worker). I can only attempt to draw his attention to the issue by mentioning him here and hoping that he take action.

I understand your urgency, and we have always prioritized the prevention of online scams. Therefore, our code includes provisions for using the Google Safe Browsing API to check if redirect links are safe. You can submit the phishing website to Google(You can use this link to submit: https://safebrowsing.google.com/safebrowsing/report_phish/), and once Google processed, the website will be automatically blocked by the URL shortener instance (if user @yuren0 has pre-configured the Google Safe Browsing API Key). Additionally, Chrome and Firefox browser users will receive a danger warning when visiting the phishing website.

Please let me know if you need any further assistance.

**Comment by yuren0** [comment]
Thanks for the feedback and reminders, website redirects suspected of phishing attacks have been removed.

**Comment by yuren0** [comment]
Thanks for the feedback and reminders, website redirects suspected of phishing attacks have been removed.
&nbsp;


Fete_雨人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月5日(星期五) 中午12:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xyTom/Url-Shorten-Worker] [URGENT] Disabling malicious redirect http://yuren.me/QnZYED (Issue #63)















嗨，朱利安

感谢您提请我们注意这一问题。然而，我很遗憾地通知你，我们不能采取直接行动，以关闭有关的链接，因为它不属于我们管理的实例之一。这是因为URL缩短器是一个开源项目，任何人都可以使用项目的源代码部署服务。

经过初步调查，似乎被利用的URL ***@***.***（对应的存储库地址：https://github.com/yuren0/Url-Shorten-Worker). 我只能在这里提到他，希望他采取行动，以提请他注意这一问题。

我理解你的紧迫性，我们一直优先考虑防止网上诈骗。因此，我们的代码包含使用Google安全浏览API检查重定向链接是否安全的规定。您可以将钓鱼网站提交给谷歌（您可以使用此链接提交：https://safebrowsing.google.com/safebrowsing/report_phish/），一旦谷歌处理，该网站将被自动封锁的URL ***@***.***已经预先配置了Google安全浏览API密钥）。此外，Chrome和Firefox浏览器用户在访问钓鱼网站时会收到危险警告。

请让我知道，如果你需要任何进一步的协助。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
你收到这个是因为你被提到了。消息ID:< xyTom /Url-Shorten-Worker/议题/ 63 / ***@***.***和&gt;

**Comment by jdrangosch** [comment]
Hi @xyTom and @yuren0 

Thank you very much both for the actions taken. 

Have a great day.
